language: ruby
rvm:
  - 2.0.0-p648
  - 2.1.8
  - 2.2.3
  - 2.3.1
env:
  - 
cache: bundler
script: bundle install && bundle exec rspec spec/
deploy:
  provider: rubygems
  api_key: $GEM_TOKEN
  gem: kontena-plugin-aws
  on:
    tags: true
